# Generated by Django 4.2.2 on 2023-06-10 09:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDbModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FridgeDbModel',
            fields=[
                ('fridge_id', models.UUIDField(default=uuid.UUID('079cfccc-4554-4754-873f-3e5710895aa0'), editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDbModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fridge_db_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='genie.fridgedbmodel')),
            ],
        ),
    ]
