# Generated by Django 4.2.2 on 2023-06-10 09:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgedbmodel',
            name='fridge_id',
            field=models.UUIDField(default=uuid.UUID('812fa894-251d-43f3-b2d1-4679a734c169'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='IngredientDbModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.FloatField(default=1)),
                ('pic_url', models.CharField(max_length=100)),
                ('category', models.ForeignKey(choices=[], null=True, on_delete=django.db.models.deletion.SET_NULL, to='genie.categorydbmodel')),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genie.fridgedbmodel')),
            ],
        ),
    ]
