# Generated by Django 4.2.2 on 2023-06-10 10:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0002_alter_fridgedbmodel_fridge_id_ingredientdbmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientdbmodel',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 10, 10, 24, 53, 80418, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='ingredientdbmodel',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 10, 10, 24, 53, 80418, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fridgedbmodel',
            name='fridge_id',
            field=models.UUIDField(default=uuid.UUID('64fb5f6e-d8e6-4fc3-9247-3fb35a9d8879'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredientdbmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='genie.categorydbmodel'),
        ),
    ]
