# Generated by Django 4.2.2 on 2023-06-11 09:26

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0003_ingredientdbmodel_create_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorydbmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='categorydbmodel',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fridgedbmodel',
            name='fridge_id',
            field=models.UUIDField(default=uuid.UUID('670648c9-7ad6-4248-9f5d-a970e47092e4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredientdbmodel',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 11, 9, 26, 44, 377505, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ingredientdbmodel',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 11, 9, 26, 44, 377505, tzinfo=datetime.timezone.utc)),
        ),
    ]
