# Generated by Django 4.2.2 on 2023-06-21 09:03

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0005_alter_fridgedbmodel_fridge_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgedbmodel',
            name='fridge_id',
            field=models.UUIDField(default=uuid.UUID('92319ba6-f991-4875-bfc2-4f11da18344b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredientdbmodel',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 21, 9, 3, 14, 811160, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ingredientdbmodel',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 21, 9, 3, 14, 811160, tzinfo=datetime.timezone.utc)),
        ),
    ]
