# Generated by Django 4.2.2 on 2023-06-21 09:26

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0007_alter_fridgedbmodel_fridge_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgedbmodel',
            name='fridge_id',
            field=models.UUIDField(default=uuid.UUID('792fd599-a744-4331-ac74-6e180c69b534'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredientdbmodel',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 21, 9, 26, 43, 549824, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ingredientdbmodel',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 21, 9, 26, 43, 549824, tzinfo=datetime.timezone.utc)),
        ),
    ]
